version: '3'

services:
  spark:
    build:
      context: ./spark
    ports:
      - "4040:4040"
      - "8080:8080"
      - "7077:7077"
    networks:   # Add the 'my_network' network to the Spark container
      - my_network
    # Other configurations for the Spark container

  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432" # PostgreSQL port
    environment:
      POSTGRES_USER: pg-admin
      POSTGRES_PASSWORD: beterraba123
      POSTGRES_DB: elt-pg
    networks:   # Add the 'my_network' network to the PostgreSQL container
      - my_network
    # Other configurations for the PostgreSQL container

volumes:
  spark_data:  # Define volume for Spark data persistence
  spark_logs:  # Define volume for Spark logs

networks:
  my_network:  # Create a custom network named 'my_network'
    driver: bridge   # You can use 'bridge' or any other appropriate network driver

