version: '3'
services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: pg-admin
      POSTGRES_PASSWORD: beterraba123
      POSTGRES_DB: elt-pg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_network

  spark-master:
    image: bitnami/spark:latest
    container_name: spark_master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    networks:
      - custom_network

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark_worker_1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - custom_network

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark_worker_2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - custom_network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    command: "start-notebook.sh --NotebookApp.token='your_jupyter_token'"
    volumes:
      - jupyter_data:/home/jovyan/work  # Mount a volume for Jupyter notebooks and files
      - ./inbound:/home/jovyan/work/inbound  # Mount the inbound directory into the Jupyter container
    networks:
      - custom_network

volumes:
  postgres_data:  # Volume for Postgres data
  jupyter_data:   # Volume for Jupyter notebook files and data

networks:
  custom_network:
    driver: bridge
