# Use a base image with Java and Spark pre-installed
FROM bitnami/spark:latest

# Optionally, you can add additional configurations or copy files to the container if needed
# COPY your_additional_files /path/in/container
# ENV some_environment_variable=value

# Expose Spark ports (change the ports accordingly if needed)
EXPOSE 4040 8080 7077