# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Optionally, you can add additional configurations or copy files to the container if needed
# COPY your_additional_files /path/in/container
# ENV some_environment_variable=value

# Expose PostgreSQL port (default is 5432)
EXPOSE 5432